- hosts: localhost
  connection: local
  vars:
    sns_topic: arn:aws:sns:us-east-1:325086054855:NotificationTopic
    autoscaling_group: kubota-prod-BastionStack-1F8UTQEN01E96-BastionAutoScalingGroup-RZ8DX52SZ0F5
    low_cpu_asg: Autoscaling-low-cpu-alarm
    high_cpu_asg: Autoscaling-high-cpu-alarm 
    
  roles:
    - cloudwatch
    